# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yeonwoo Choi
title: DGIST Integrated B.S.-M.S.-Ph.D.
email: cyw040306@dgist.ac.kr
Linkedin: https://www.linkedin.com/in/yeonwoo-choi-48b6a72b5

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: CTypeCharger
instagram_username: chlaaanoeydn_36

# About Section
about_profile_image: images/profile.jpg
about_content: |
  Hi, my name's Yeonwoo Choi and I am an integrated B.S.–M.S.–Ph.D. student at DGIST (Daegu Gyeongbuk Institute of Science and Technology), South Korea, focusing on ROS 2, middleware, and networked robotic systems.

  I am most skilled in: <mark>ROS2</mark> and <mark>DDS</mark>

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: DGIST
        sub_title: Integrated B.S.–M.S.–Ph.D. Program
        caption: 2023 - Present
        description: | 
          Research focus: ROS2, middleware, and wireless network for robotic systems.

  - title: News
    layout: list
    content:
      - layout: left
        title: Merit Award, Undergraduate Group Research Program (UGRP)
        caption: 2026-01
        description: | 
          Received the Merit Award in the Undergraduate Group Research Program (UGRP) for the project "Development of a Personality Assessment Method Using Thermal Perception EEG."
      - layout: left
        title: Joined Integrated B.S.–M.S.–Ph.D. Program at DGIST
        caption: 2026-01
        description: |
          Started the Integrated B.S.–M.S.–Ph.D. Program in EECS, DGIST.

  - title: Publications
    layout: list
    content:
      - layout: top-middle
        title: "Discovery Storm: Scalability Analysis of DDS and Zenoh in Large-Scale Wireless Robotic Networks"
        sub_title: under review
        caption: 2026
        link: https://example.com
        description: |
          Coming soon.

  - title: Awards
    layout: list
    content:
      - layout: list
        title: Merit Award
        sub_title: Undergraduate Group Research Program (UGRP), DGIST
        caption: Jan 2026

      - layout: list
        title: Encouragement Award
        sub_title: 2025 Brain Engineering Society of Korea Summer Workshop
        caption: Jul 2025

  - title: Research Experience
    layout: list
    content:
      - layout: list
        title: CSI Lab, DGIST
        sub_title: Undergraduate Researcher
        caption: May 2025 - Present

      - layout: list
        title: DGIST (UGRP)
        sub_title: Undergraduate Group Research Program
        caption: Mar 2025 - Present

      - layout: list
        title: BRAIN Lab, DGIST
        sub_title: Undergraduate Researcher
        caption: Feb 2025 - Dec 2025

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
